server:
  port: 8021 
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gotkdqja@gmail.com
    password: sgxscmxzimydcafq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
   view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp   
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sb_c_2021_2nd_t?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.psw.exam.demo.vo
custom:
  needToChangePasswordFreeDays: 90
  siteMainUri: http//localhost:8021/
  siteName: 커뮤니티페이지
  emailFrom: gotkdqja@localhost
  emailFromName: 커뮤니티페이지알림봇
  logging:
    dir: log
    level: debug   